---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  labels:
    app.kubernetes.io/instance: x-ray
    app.kubernetes.io/name: x-ray
  disableNameSuffixHash: false

secretGenerator: []

configMapGenerator: []
