---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: x-ray
  namespace: x-ray
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "watch", "list"]
