---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: x-ray
  namespace: x-ray
subjects:
- kind: ServiceAccount
  name: x-ray
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: x-ray
