configVersion: 1
router:
    topology:
        local:
            requiredServiceTypes: 'jfxr,jfxana,jfxidx,jfxpst'
shared:
    logging:
        consoleLog:
            enabled: false
    jfrogUrl: "http://artifactory-xray.artifactory/"
    database:
        type: postgresql
        driver: org.postgresql.Driver
    rabbitMq:
        erlangCookie:
            value: ""
server:
    mailServer: ""
    indexAllBuilds: ""
